### ISSUE TITLE
How to set the version that pip is building?

### ISSUE THREAD

**Issue by SuperSandro2000** [cmroche/greeclimate#46]
I am currently fixing a bunch of packages in nixpkgs which have the version number not set right.
How is a distro supposed to set the version number from a tarball? dd638dc81f50d6d36eccffb90d504c2ad6229e43 leaves no hint how that should be done.

**Comment by cmroche** [comment]
Carrying the conversation from https://github.com/cmroche/moonraker-api/commit/e5ca8ab60d2839e150a81182fbe65255d84b4e4e to this issue for simplicity since they are both my packages and present the same problem.

semantic-release required me to remove that variable in order to work. I might take a look this weekend and see if there is another approach to reconcile these use cases, though I am uncertain that the tool can be avoided.

Another thought, I could write out a version.txt or something and commit alongside the CHANGELOG update, would this help?

**Comment by dotlambda** [comment]
> Another thought, I could write out a version.txt or something and commit alongside the CHANGELOG update, would this help?

setup.py could read the version from that file

**Comment by cmroche** [comment]
I wouldn’t be able to do that though for the normal releases, so I would still need to find a way to separate those cases clearly so that it’s compatible with the semantic-release pipeline. Feels like it probably isn’t complex, but I’ll need to first figure our how the PyPI plugin for semantic-release is working.

**Comment by cmroche** [comment]
@dotlambda Should be resolved for both packages now, by submitting the generated **setup.cfg** with the version generated by the auto-release pipeline.

**Comment by dotlambda** [comment]
Thank you!
